---
Name: subsitedomains
After:
  - 'subsites/*'
---
Subsite:
  extensions:
    - SubsiteLinkExtension


Injector:
  SubsitesVirtualPage_Controller: 
    class: OPSubsitesVirtualPage_Controller
  SiteTreeURLSegmentField:
    class: SubsiteSiteTreeURLSegmentField
