---
Name: subsitedomains
After:
  - 'subsites/*'
---
SilverStripe\Subsites\Model\Subsite:
  extensions:
    - OP\SubsiteLinkExtension


SilverStripe\Core\Injector\Injector:
  SilverStripe\CMS\Forms\SiteTreeURLSegmentField:
    class: OP\SubsiteSiteTreeURLSegmentField
    
SilverStripe\Admin\ModalController:
  extensions:
    - OP\ModalControllerExtension
